#!/usr/bin/env bash

# this is beyond impractical
# but it works..?

# clipboard history with images using fzf, ueberzugpp, and xclip.
# png images only, since that's what xclip supports.
# every clip is created as an empty file with touch (yes, I know)

# bind `cliphist add` and `cliphist out` to shortcuts
# to copy text, press your shortcut key for add,
# to copy images, first copy normally, then run your shortcut key
# you'll also need any fzfub wrapper for image previews in fzf
# if you're using dwm or similar, you may need to ensure that the
# window class `fzfmenu` or title `fzf` has floating property

hist="$HOME/.cache/hist/"
placeholder="<NEWLINE>"

output() { # copy directly from command output
		clip=$(xclip -i -f -selection clipboard 2>/dev/null)
}

write() { # write current clip into directory, txt or img
		[ -e "$hist" ] || notify-send "Creating directory $hist..."; mkdir -p $hist
		isimg=$(xclip -selection clipboard -o -t TARGETS | grep png)

		if [[ -n $isimg ]]; then
		   	xclip -selection clipboard -t image/png -o > $hist/$(date '+%a_%b%d_%H%M%S').png
		else
				clip=$(xclip -o -selection primary | xclip -i -f -selection clipboard 2>/dev/null)
				multiline=$(echo "$clip" | sed ':a;N;$!ba;s/\n/'"$placeholder"'/g')
				touch "$hist/$multiline"
		fi
		notify-send " clipped"
}

sel() { # select from clip history and re-copy to clipboard
		st -c fzfmenu -n fzfmenu -T fzf -g "100x12-260+270" -e dash -c "fzfub $hist > $hist/txt"
		selection=$(\cat $hist/txt | sed 's/.*\.cache\/hist\///')
		if [[ -n $(file -b --mime-type $hist/$selection | grep png) ]]; then 
				xclip -selection clipboard -t image/png -i $hist/$selection
		else echo $selection | sed "s/$placeholder/\n/g" | xclip -i -selection clipboard
		fi
		notify-send "clipped "

}

case "$1" in
		add) write ;;
		out) output && write ;;
		sel) sel ;;
		*) printf "$0 | File: $hist\n\nadd - copies primary selection to clipboard, and adds to history directory\nout - pipe commands to copy output to clipboard, and add to history directory\nsel - select from history file with fzf and recopy!\n" ; exit 0 ;;
esac
