#!/usr/bin/env bash

# mpc (and mpd) seem to have trouble with complex filenames. still working on a solution to this
# relative path to mpd's music directory *must* be used. absolute path will not be read by mpd.

		if command -v fd >/dev/null; then 
				file=$(fd .mp3 ~/Music -p -t f | sed "s|^/home/$USER/Music/||" | dmenu -i -l 1) || exit 0
		else 
				file=$(find ~/Music -type f -name "*.mp3" | sort | sed "s|^/home/$USER/Music/||" | dmenu -i -l 1) || exit 0
		fi

notify-send "Playing $file" && mpc insert "$file" && mpc next >/dev/null
