#!/usr/bin/env bash

pidof -x playerctl-loop >/dev/null 2>&1 || playerctl-loop >/dev/null 2>&1 &

music=termusic
browser=firefox

browserstatus=$(playerctl --player=$browser status)
musicstatus=$(playerctl --player=$music status)

[[ $musicstatus == "Playing" ]] && icon="🎵 " || icon="❚❚ "

if [[ $browserstatus == "Playing" ]]; then
    player=$browser
    icon=" 🦊 "
    format=$(playerctl metadata --player=$player --format '{{ trunc(title,25) }}')
else
    player=$music
    format=$(playerctl metadata --player=$player --format '{{ trunc(artist,17) }} - {{ trunc(title,17) }}')
fi

case $BLOCK_BUTTON in
  1) $player ;;
  2) playerctl --player=$player play-pause; pkill -RTMIN+11 "${STATUSBAR:-dwmblocks}" ;;
  3) setsid -w -f "$TERMINAL" -e pulsemixer; pkill -RTMIN+11 "${STATUSBAR:-dwmblocks}" ;;
  4) playerctl --player=$player volume 0.05+ ;;
  5) playerctl --player=$player volume 0.05- ;;
  6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo -e "$icon$format"

# If you want responsive updates from dwmblocks, put these in a separate script
# playerctl -p termusic metadata title >/dev/null && kill -45 "$(pidof "${STATUSBAR:-dwmblocks}")" || break
# playerctl -p firefox metadata title > /dev/null >/dev/null && kill -45 "$(pidof "${STATUSBAR:-dwmblocks}")" || break
