#!/usr/bin/env bash

# Sensor info
CPU_TEMP=$(sensors | awk '/^Tdie/ {print substr($2,2)}')
MEM_USE=$(free -m | awk '/^Mem/ {print ($3)/1024}'| cut -c-4)
CPU_USE=$(iostat -c | awk 'NR>=4 && NR <=4' | awk '{print "User CPU:  "$1"%\n\nSystem CPU: ",$3"%"}')
GPU_TEMP=$(sensors | awk '/^edge/ {print substr($2,2)}')
FAN_SPEED=$(sensors | awk '/^fan/ {print $2" "$3}')

# Show warnings if CPU or GPU temp are high
case $CPU_TEMP in
		[7-9][6-9]|[8-9][0-9]|100) COLOR="#bf616a" && CPU_WARN=" " ;;  # Greater than 75
		[6][6-9]|7[0-5]) COLOR="#ebcb8b" ;;            # Between 66 and 75
		*) COLOR="#a3be8c" ;;                          # 65 or below
esac

case $GPU_TEMP in
		[7-9][1-9]|[8-9][0-9]|100) GPU_WARN="  $GPU_TEMP" ;;  # Greater than 71
		[5][1-9]|70) GPU_WARN=" 󰢮 $GPU_TEMP" ;;            # Between 51 and 70
		*) ;;                          # 50 or below
esac

# Send to bar
echo "$GPU_WARN$CPU_WARN  "$CPU_TEMP  $MEM_USE"g"

# Clicking on bar
case $BLOCK_BUTTON in
		1) setsid -w -f "$TERMINAL" -e htop ;;
		3) notify-send -t 10000 -h string:bgcolor:$COLOR Stats "$CPU_USE\n\nGPU: 󰢮 $GPU_TEMP\n\nFan Speed:  $FAN_SPEED" ;;
		6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
