#!/usr/bin/env bash

# (most of) my imagemagick preset commands
# use with photomenu and/or my version of
# fzfub as an image quick-edit menu!

WATERMARK=~/pics/watermark.png
NOTIFYCMD=$(which dunstify 2>/dev/null || which notify-send 2>/dev/null) # dunstify if available, otherwise notify-send

watermark() { for IMG in $@; do
		    	composite -compose multiply -gravity SouthWest -geometry +99+99 $WATERMARK $IMG "${IMG}.watermark" && $NOTIFYCMD "Watermarked $IMG."
		done ;}

convpng() { for IMG in $@; do
				mogrify -format png $IMG && $NOTIFYCMD "Converted $IMG to png."
		done ;}
convjpg() { for IMG in $@; do
				mogrify -format jpg $IMG && $NOTIFYCMD "Converted $IMG to jpg."
		done ;}

border() { for IMG in $@; do
		magick $IMG -bordercolor black -border 50x50 "$IMG.border" && $NOTIFYCMD "Added black border to $IMG."
		done ;}

wborder() { for IMG in $@; do
		magick $IMG -bordercolor white -border 50x50 "$IMG.border" && $NOTIFYCMD "Added white border to $IMG."
		done ;}

bw() { for IMG in $@; do
		magick $IMG -colorspace Gray "$IMG.bw" && $NOTIFYCMD "B&W'd $IMG."
		done ;}

transparency() { for IMG in $@; do
		magick $IMG -alpha off -fuzz 10% -fill none -draw "alpha 0,0 floodfill" \( +clone -alpha extract -blur 0x2 -level 50x100% \) -alpha off -compose copy_opacity -composite "$IMG.trnsprnt" && $NOTIFYCMD "Removed background from $IMG."
		done ;}

transparencyrecopy() { for IMG in $@; do
		magick $IMG -alpha off -fuzz 10% -fill none -draw "alpha 0,0 floodfill" \( +clone -alpha extract -blur 0x2 -level 50x100% \) -alpha off -compose copy_opacity -composite "$IMG.trnsprnt"
		xclip -i -selection clipboard -t image/png "$IMG.trnsprnt"
		$NOTIFYCMD -i "$IMG.trnsprnt" "$IMG background removed and recopied "
		done ;}

scale() { for IMG in $@; do
		mogrify $IMG -scale 50% $IMG.scale && $NOTIFYCMD "Scaled $IMG to 50%."
		done ;}

flip() { for IMG in $@; do
		magick $IMG -flop $IMG.flip && $NOTIFYCMD "Horizontally flipped $IMG."
		done ;}

vflip() { for IMG in $@; do
		magick $IMG -flip $IMG.vflip && $NOTIFYCMD "Vertically flipped $IMG."
		done ;}


case $1 in
		wm) 
				shift
				watermark "$@" ;;
		png) 
				shift
				convpng "$@" ;;
		jpg) 
				shift
				convjpg "$@" ;;
		border)
				shift
				border "$@" ;;
		wborder)
				shift
				wborder "$@" ;;
		bw)
				shift
				bw "$@" ;;
		transparency)
				shift
				transparency "$@" ;;
		transparencyrecopy)
				shift
				transparencyrecopy "$@" ;;
		scale)
				shift
				scale "$@" ;;
		flip)
				shift
				flip "$@" ;;
		vflip)
				shift
				vflip "$@" ;;

		*) notify-send "imgmgk🪄" "1st arg: wm, png, jpg, border, wborder, bw, transparency, transparencyrecopy, scale, flip, vflip. Further args: files." && exit 0 ;;
esac
