#!/usr/bin/env bash

### Full credit for this script to https://github.com/TheGassyNinja

export DISPLAY=:0
current=$(date +%H-%M-%S-%d-%m-%Y).png
if [[ -z "${1}" ]]; then
   import -window root "${HOME}/${current}" # All screen
else
   import "${HOME}/${current}" # Custom area screenshot
fi
notify-send "Screenshot ${current} taken successfully!"
